### ISSUE TITLE
EXDEV: cross-device link not permitted, rename '/tmp/upload_02b9eaa79cab07b75b41a5a6ffbc98cc' -> '//{new_file_path}'

### ISSUE THREAD

**Issue by 3dWaRdeJ** [SoftwareBrothers/admin-bro-upload#10]
Hi, learn your sysytem - it`s great

Found this issue when working with local provider   
I found the same problem on https://stackoverflow.com/questions/8579055/how-do-i-move-files-in-node-js

I found why it`s not work - the reason is this part of code in (and because my LInux distro use for directory /tmp a [tmpfs](https://wiki.archlinux.org/index.php/tmpfs) filesystem)  
**/src/features/upload-file/providers/local-provider.ts**

```ts
  public async upload(file: UploadedFile, key: string): Promise<any> {
    const filePath = this.path(key)
    await fs.promises.mkdir(path.dirname(filePath), { recursive: true })
    await fs.promises.rename(file.path, filePath)
  }
```

As I understand AdminBro firstly upload file to **/tmp** directory and after move file to project dir  
But in code use function **fs.rename** and it`s a problem because **rename** use only when you move file in the same mounting point of filesystem  

see https://man7.org/linux/man-pages/man2/rename.2.html
  
The possible solution is to use function **move** of module **fs-extra** instead **fs** 

```ts
  import * as fs from 'fs-extra'    

  public async upload(file: UploadedFile, key: string): Promise<any> {
    const filePath = this.path(key)
    await fs.move(file.path, filePatch, {overwrite: true})
  }
```

and replace other **fs** function in file by their clone in **fs-extra**

**Comment by wojtek-krysiak** [comment]
You can simply solve this issue by writing your own UploadProvider (see https://beta.adminbro.com/module-@admin-bro_upload.html - section Custom Provider) - simply override the upload method and you don't need to change the codebse.

I want to introduce as little dependencies as possible that is why I would suggest that.
