### ISSUE TITLE
Change behaviour defined in build-path.ts

### ISSUE THREAD

**Issue by mad93** [SoftwareBrothers/admin-bro-upload#12]
Is possible to change the behaviour defined by build-path.ts file that is overriding the key.

We are using a custom provider, and this code is messing with the value stored on the field of the database that is defined as key. How we can customize this behaviour?

Thank you

**Comment by wojtek-krysiak** [comment]
In the beta version there is a config: https://beta.adminbro.com/module-@admin-bro_upload.html#UploadPathFunction

**Comment by wojtek-krysiak** [comment]
and beta is now @next - so closing this one
