### ISSUE TITLE
admin_bro_1.buildFeature is not a function. update adminbro version in all packages

### ISSUE THREAD

**Issue by AlexeyVlasenko** [SoftwareBrothers/admin-bro-upload#3]
Hi! I'm using this module follows documentation, but receive this:

````
const uploadFeature = admin_bro_1.buildFeature({
                                      
TypeError: admin_bro_1.buildFeature is not a function

**Comment by wojtek-krysiak** [comment]
which modules do you use?

and try to remove node_modules and make sure you have the latest admin bro version

**Comment by AlexeyVlasenko** [comment]
`"@admin-bro/express": "^3.0.0",
    "@admin-bro/mongoose": "^1.0.0",
    "@admin-bro/upload": "^1.0.0",
    "admin-bro": "^2.2.4",
`
Already tried to remove node_modules and install them again.

**Comment by wojtek-krysiak** [comment]
do you use typescript? can you paste more stacktrace and your code?

**Comment by AlexeyVlasenko** [comment]
Nope, JS.

https://gist.github.com/AlexeyVlasenko/ef03ba7f578ed41c04caceb12afae3c8

**Comment by wojtek-krysiak** [comment]
can you go there (Documents/Work/Node/app/node_modules/@admin-bro/upload/build/features/upload-file/upload-file.feature.js:146:39) and console log AdminBro.VERSION?

**Comment by AlexeyVlasenko** [comment]
AdminBro version is:  2.9.0

**Comment by AlexeyVlasenko** [comment]
Okay, i'm sorry, that's my fault.
For some reason version of `admin-bro` wasn't up-to-date.
After upgrading it to `3.2.5` all works. Thanks!

**Comment by wojtek-krysiak** [comment]
it might not be you fault. I think that it used version from adapter. We will have to update adminbro dependencies everywhere. So leaving this open

**Comment by wojtek-krysiak** [comment]
mongoose beta has the latest version so closing this one
