### ISSUE TITLE
applying two upload functionalities for a single model at the same time

### ISSUE THREAD

**Issue by Amixengineer** [SoftwareBrothers/admin-bro-upload#5]
Hello dear brothers,

it seems that when we apply two upload functionalities for one resource at the same time they mix up together and one of them tend not to show up. 

company.blog.js
```
const AdminBro = require('admin-bro');
const { Blog } = require('../../models/Blog');
const { sort, timestamps } = require('../sort');
const uploadFeature = require('@admin-bro/upload');
const path = require('path');
const fs = require('fs');
/** @type {AdminBro.ResourceOptions} */
const options = {
    name: 'Blog (customize field)',
    sort,
    properties: {
        ...timestamps,
        slug: {
            position: 0,
        },
        description: {
            isVisible: {list: false, edit: true, filter: false, show: true},
            position: 1,
            components: {
                edit: AdminBro.bundle('../components/custom-fonts.edit.tsx')
            }
        },
        tags: {
            isVisible: {list: false, edit: true, filter: true, show: true},
            position: 8
        },
        keywords: {
            isVisible: {list: false, edit: true, filter: true, show: true},
            position: 9
        },
        draftMode: {
            isVisible: {list: true, edit: true, filter: true, show: true},
        },
        _id: {
            isVisible: { list: false, edit: false, filter: false, show: false},
        },
    },
};


module.exports = {
    options,
    resource: Blog,
    features: [
        uploadFeature({
            provider: { local: { bucket: path.join(__dirname, '../../uploads') } },
            properties: {
                key: 'featuredPhoto.path',
                bucket: 'featuredPhoto.folder',
                mimeType: 'featuredPhoto.type',
                size: 'featuredPhoto.size',
                filename: 'featuredPhoto.filename',
                file: 'featuredPhoto',
            },
        }),
        uploadFeature({
            provider: { local: { bucket: path.join(__dirname, '../../uploads') } },
            properties: {
                key: 'thumbnailPhoto.path',
                bucket: 'thumbnailPhoto.folder',
                mimeType: 'thumbnailPhoto.type',
                size: 'thumbnailPhoto.size',
                filename: 'thumbnailPhoto.filename',
                file: 'thumbnailPhoto',
            },
        }),
    ],
};
```

Models - Blog.js

```
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const slug = require('slugs');

const blogSchema = new mongoose.Schema({
	title: {
		type: String,
		trim: true,
		required: 'لطفا یک عنوان برای مقاله وارد کنید.'
	},
	slug: {
		type: String,
		trim: true,
		required: 'لطفا لینک مقاله را وارد کنید.'
	},
	description: {
		type: String,
		required: 'توضیحات مربوط به مقاله را وارد کنید.'
	},
	category: [{
		type: mongoose.Schema.Types.ObjectId,
		ref: 'Category',
	}],
	subCategory: [{
		type: mongoose.Schema.Types.ObjectId,
		ref: 'SubCategory',
	}],
	tags: {
		type: [String]
	},
	authors: { type: mongoose.Schema.ObjectId, ref:'Admin', required: 'نام نوینسده را انتخاب کنید' },
	keywords: {
		type: [String]
	},
	draftMode: {
		type: Boolean,
		default: false
	}
	
}, { timestamps: true } );



blogSchema.virtual('admins', {
	ref: 'Admin',
	localField: 'authors',
	foreignField: '_id',
});

const FeaturedPhoto = new mongoose.Schema({
	path: String,
	type: String,
	size: Number,
	folder: String,
	filename: String,
  });


const ThumbnailPhoto = new mongoose.Schema({
	path: String,
	type: String,
	size: Number,
	folder: String,
	filename: String,
});


const Blog = mongoose.model('Blog', { blogSchema, featuredPhoto: FeaturedPhoto, thumbnailPhoto: ThumbnailPhoto, }, );
module.exports = { blogSchema, Blog, ThumbnailPhoto, FeaturedPhoto, };
```

thanks for the support and maintanance.

**Comment by LahmerIlyas** [comment]
I'm looking for this feature too, anyone can help

**Comment by LahmerIlyas** [comment]
Can any body respond to this plz.

**Comment by Amixengineer** [comment]
@LahmerIlyas I think they are occupied by updating new changes on admin bro itself.

**Comment by wojtek-krysiak** [comment]
yep. working on v3.3 and tomorrow we will be fixing bugs related to this issue (hopefully this will be it).

**Comment by Amixengineer** [comment]
Hello dear Wojtek, no updates related to this issue yet ?

**Comment by wojtek-krysiak** [comment]
I am just publishing it right now in beta

**Comment by wojtek-krysiak** [comment]
ok - it is there: 1.2.0-beta.2

readme is here: https://github.com/SoftwareBrothers/admin-bro-upload/blob/391b63976111464bf3c493895917fa79f0da9bed/src/index.doc.md

and check out this crazy example: https://github.com/SoftwareBrothers/admin-bro-upload/blob/beta/example-app/src/admin/resources/multi/multi.resource.ts (4 uploads in one resource and one is an Array)

**Comment by Amixengineer** [comment]
@wojtek-krysiak Thanks for setting aside time for addressing this bug.
God bless you.

**Comment by wojtek-krysiak** [comment]
np, please let me know after testing it if it works

**Comment by Amixengineer** [comment]
Hello, I have set it up. Although I use file in properties, I don't get DropZone.

company.blog.js
```
const uploadFeatureFor = (multiple = true) => (
    uploadFeature ({
        provider: { local: { bucket: path.join(__dirname, '../../uploads/featured') } },
        multiple,
        properties: {
            filePath: 'featuredPhoto.filePath',
            fileToDelete: 'featuredPhoto.fileToDelete',
            key: 'featuredPhoto.path',
            mimeType: 'featuredPhoto.type',
            bucket: 'featuredPhoto.folder',
            size: 'featuredPhoto.size',
            file: 'featuredPhoto',
        },
    }),
    uploadFeature({
        provider: { local: { bucket: path.join(__dirname, '../../uploads/thumbnail') } },
        multiple,
        properties: {
            filePath: 'thumbnailPhoto.filePath',
            fileToDelete: 'thumbnailPhoto.fileToDelete',
            key: 'thumbnailPhoto.path',
            mimeType: 'thumbnailPhoto.type',
            bucket: 'thumbnailPhoto.folder',
            size: 'thumbnailPhoto.size',
            file: 'thumbnailPhoto',
        },
    })
)

module.exports = {
    options,
    resource: Blog,
    features: [
        uploadFeatureFor()  
    ],
};
```


Blog.js - my Model
```
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const slug = require('slugs');



const blogSchema = new mongoose.Schema({
	title: {
		type: String,
		trim: true,
		required: 'لطفا یک عنوان برای مقاله وارد کنید.'
	},
	slug: {
		type: String,
		trim: true,
		required: 'لطفا لینک مقاله را وارد کنید.'
	},
	description: {
		type: String,
		required: 'توضیحات مربوط به مقاله را وارد کنید.'
	},
	category: [{
		type: mongoose.Schema.Types.ObjectId,
		ref: 'Category',
	}],
	subCategory: [{
		type: mongoose.Schema.Types.ObjectId,
		ref: 'SubCategory',
	}],
	tags: {
		type: [String]
	},
	authors: { type: mongoose.Schema.ObjectId, ref:'Admin', required: 'نام نوینسده را انتخاب کنید' },
	keywords: {
		type: [String]
	},
	draftMode: {
		type: Boolean,
		default: false
	},
}, { timestamps: true } );

const FeaturedPhoto = new mongoose.Schema({
	path: String,
	type: String,
	size: Number,
	folder: String,
	filename: String,
});


const ThumbnailPhoto = new mongoose.Schema({
	path: String,
	type: String,
	size: Number,
	folder: String,
	filename: String,
});


blogSchema.virtual('admins', {
	ref: 'Admin',
	localField: 'authors',
	foreignField: '_id',
});


const Blog = mongoose.model('Blog', { blogSchema, FeaturedPhoto, ThumbnailPhoto });

module.exports = { blogSchema, Blog, FeaturedPhoto, ThumbnailPhoto};
```

The image
<img width="1199" alt="Screen Shot 1399-07-20 at 16 53 06" src="https://user-images.githubusercontent.com/34276557/95679870-7944d280-0be2-11eb-8a83-b60798c5fb2b.png">


Thanks for support,

**Comment by wojtek-krysiak** [comment]
you have to use latest beta of admin bro

**Comment by Amixengineer** [comment]
@wojtek-krysiak I changed it to  "admin-bro": "^3.3.0-beta.21" but I get around 20 errors in my console even when I shift to single upload feature. I also lost my custom quill component

console log
<img width="1194" alt="Screen Shot 1399-07-21 at 00 39 17" src="https://user-images.githubusercontent.com/34276557/95690339-dad96100-0c23-11eb-9a9d-608994d1eb75.png">

resource window
<img width="1088" alt="Screen Shot 1399-07-21 at 00 53 27" src="https://user-images.githubusercontent.com/34276557/95690518-5982ce00-0c25-11eb-82b7-424f9abeb7ee.png">


thanks for maintanence,

**Comment by wojtek-krysiak** [comment]
try to remove node_modules and install them again. Also remove .adminbro folder.

**Comment by wojtek-krysiak** [comment]
if that wont help remove quill related components and see if uplosf work without them.

**Comment by Amixengineer** [comment]
@wojtek-krysiak Thanks for your hints, 

now I have got everything back again but the only problem is I do not have a dropZone for one upload image feature. 

<img width="1067" alt="Screen Shot 1399-07-21 at 22 10 39" src="https://user-images.githubusercontent.com/34276557/95779947-e4bc9c00-0cd7-11eb-9b76-ecdc2c04220b.png">
<img width="1066" alt="Screen Shot 1399-07-21 at 22 10 31" src="https://user-images.githubusercontent.com/34276557/95779950-e5553280-0cd7-11eb-96ac-a98682c07a6f.png">




regarding to Quill I tried to add things like Embedded URL for videos, anchor links, Html editor, encoded 64 image as well as custom fonts through the component. I am not sure that the upgraded one by adminBro supports adding custom fonts or not.

**Comment by wojtek-krysiak** [comment]
what are your uploadFeature settings (properties)

**Comment by Amixengineer** [comment]
here you are,

const uploadFeatureFor = (multiple = true) => (
    uploadFeature ({
        provider: { local: { bucket: path.join(__dirname, '../../uploads/featured') } },
        multiple,
        properties: {
            filePath: 'featuredPhoto.filePath',
            fileToDelete: 'featuredPhoto.fileToDelete',
            key: 'featuredPhoto.path',
            mimeType: 'featuredPhoto.type',
            bucket: 'featuredPhoto.folder',
            size: 'featuredPhoto.size',
            file: 'featuredPhoto.file',
        },
    }),
    uploadFeature({
        provider: { local: { bucket: path.join(__dirname, '../../uploads/thumbnail') } },
        multiple,
        properties: {
            filePath: 'thumbnailPhoto.filePath',
            fileToDelete: 'thumbnailPhoto.fileToDelete',
            key: 'thumbnailPhoto.path',
            mimeType: 'thumbnailPhoto.type',
            bucket: 'thumbnailPhoto.folder',
            size: 'thumbnailPhoto.size',
            file: 'thumbnailPhoto.file',
        },
    })
)

module.exports = {
    options,
    resource: Blog,
    features: [
        uploadFeatureFor()  
    ],
};

**Comment by wojtek-krysiak** [comment]
I see that you have multiple set - if this is true - they all should be arrays - did you set this in your ORM? or in AdminBroOptions like this:

```
resourceOptions =  {
properties.file {
  isArray: true,
},
}
```

**Comment by Amixengineer** [comment]
I used it but I am not sure if its on the correct spot

```
const { default: AdminBro } = require('admin-bro');
const AdminBroMongoose = require('@admin-bro/mongoose');
AdminBro.registerAdapter(AdminBroMongoose);
const BlogCompany = require('./companies/company.blog');
const UserCompany = require('./companies/company.user');
const AdminCompany = require('./companies/company.admin');
const CategoryCompany = require('./companies/company.category');
const SubCategoryCompany = require('./companies/company.subCategory');

const options = {
    locale: {
       // translations  go here//
    },
    resources: [AdminCompany, UserCompany, BlogCompany, CategoryCompany, SubCategoryCompany ],
    **'properties.file': {
        isArray: true,
    },**
    assets: {
        styles: [
          '/admin-styles/custom-admin.css',
          '/admin-styles/fonts.css',
        ]
    },
    rootPath: '/admin',
    branding: {
        logo: '/images/icons/mrgoogle-logo.svg',
        companyName: 'مستر گوگل',
    },
};

module.exports = options;
```

**Comment by wojtek-krysiak** [comment]
adding this:
```
// you have thi already:
'properties.file': { isArray: true },
'properties.filePath': { isArray: true },
// and the rest
```
to Property options should fix it. But you are passing it in the wrong place. Take a look at this tutorial: https://beta.adminbro.com/tutorial-customizing-resources.html - it shows you how to pass options to resources.

There is an example-app in admin-bro-upload repo (beta branch) - it has mixed properties with an array - check it out.
