### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/var/app/current/.adminbro/bundle.js'

### ISSUE THREAD

**Issue by Gr8z** [SoftwareBrothers/admin-bro-upload#8]
The module works great on my local windows. But this is the error I get when I try to upload a file on my production Linux machine (AWS EC2).

`Error: ENOENT: no such file or directory, stat '/var/app/current/.adminbro/bundle.js'`

I am using the S3 transport.

**Comment by wojtek-krysiak** [comment]
run the app in production locally, then it will create bundle.js in .adminbro
